# **Evaluación de contenidos 1 Módulo 2**
## **Ejercicios de NumPy**

1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [2]:
a1 = np. random.randint(1,50, (10))
a1

array([29, 37, 17,  1, 38, 27, 47, 15, 45, 48])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [3]:
a2 = np.empty(10, dtype=object)
a2

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [4]:
for elem in range(a1.shape[0]):
    if a1[elem] % 2 != 0:
       a2[elem] = "impar"
    else:
        a2[elem] = "par"
print(a2)
        

['impar' 'impar' 'impar' 'impar' 'par' 'impar' 'impar' 'impar' 'impar'
 'par']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [5]:
a3 = a2.reshape((2,5))
a3

array([['impar', 'impar', 'impar', 'impar', 'par'],
       ['impar', 'impar', 'impar', 'impar', 'par']], dtype=object)

5. Extrae los elementos comunes de los siguientes arrays

In [6]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
array_intersect = np.intersect1d(array1, array2)
array_intersect

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [8]:
array_df = np.setdiff1d(array1, array2)
array_df

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [9]:
print(np.where(array1 == array2))

(array([1, 3, 5, 7]),)


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [10]:
a4 = np.random.randint(0,50, (3,5))
a4

array([[21, 26, 19, 11, 48],
       [46, 48, 34, 15,  6],
       [21, 17, 17, 12, 18]])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [11]:
a5 = np.random.uniform(5,10, size = (5,3))
a5

array([[8.41198249, 6.35940251, 9.76606972],
       [6.24386716, 6.51384245, 6.64474254],
       [6.45124632, 5.03245136, 9.69362228],
       [6.82533448, 8.82431515, 5.05358892],
       [5.46913141, 5.42103159, 8.68495252]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
    - Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [12]:
a6 = np.random.randint(1,20, (2,4,7))
a6

array([[[18, 19,  7, 10,  8, 18,  3],
        [ 3,  8,  9, 15, 13, 17,  4],
        [ 8, 17, 13, 18, 12, 13,  5],
        [ 8,  1, 11,  9,  8,  1,  6]],

       [[ 2, 17, 13, 18, 17, 19, 10],
        [15,  5,  7, 12,  4, 15,  3],
        [13, 16,  2,  3,  8,  4,  9],
        [ 9, 14,  5, 17, 11, 15, 10]]])

In [13]:
a7 = np.transpose(a6, (1,2,0))
a7

array([[[18,  2],
        [19, 17],
        [ 7, 13],
        [10, 18],
        [ 8, 17],
        [18, 19],
        [ 3, 10]],

       [[ 3, 15],
        [ 8,  5],
        [ 9,  7],
        [15, 12],
        [13,  4],
        [17, 15],
        [ 4,  3]],

       [[ 8, 13],
        [17, 16],
        [13,  2],
        [18,  3],
        [12,  8],
        [13,  4],
        [ 5,  9]],

       [[ 8,  9],
        [ 1, 14],
        [11,  5],
        [ 9, 17],
        [ 8, 11],
        [ 1, 15],
        [ 6, 10]]])