# **Evaluación de contenidos 1 Módulo 2**
## **Ejercicios de NumPy**

1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [2]:
a1 = np. random.randint(1,50, (10))
a1

array([ 7, 24, 37, 15, 23,  4, 12, 33,  2, 23])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [3]:
a2 = np.empty(10, dtype=object)
a2

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [15]:
for elem in range(a1.shape[0]):
    if a1[elem] % 2 != 0:
       a2[elem] = "impar"
    else:
        a2[elem] = "par"
print(a2)
        

['impar' 'par' 'impar' 'impar' 'impar' 'par' 'par' 'impar' 'par' 'impar']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [5]:
a3 = a2.reshape((2,5))
a3

array([['impar', 'par', 'impar', 'impar', 'impar'],
       ['par', 'par', 'impar', 'par', 'impar']], dtype=object)

5. Extrae los elementos comunes de los siguientes arrays

In [6]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
array_intersect = np.intersect1d(array1, array2)
array_intersect

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [8]:
array_df = np.setdiff1d(array1, array2)
array_df

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [9]:
print(np.where(array1 == array2))

(array([1, 3, 5, 7]),)


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [10]:
a4 = np.random.randint(0,50, (3,5))
a4

array([[ 1, 14, 37, 38, 44],
       [35, 49, 20, 45, 40],
       [44, 22, 38, 39, 15]])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [11]:
a5 = np.random.uniform(5,10, size = (5,3))
a5

array([[5.63698014, 6.18312481, 8.98470996],
       [7.78522999, 6.70115449, 7.54020304],
       [9.48379137, 9.88472562, 6.94720096],
       [8.02299624, 6.39379916, 5.00249414],
       [8.84783534, 7.98034221, 7.37497166]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
    - Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [12]:
a6 = np.random.randint(1,20, (2,4,7))
a6

array([[[18, 14, 19,  7, 11, 16,  6],
        [ 2,  5, 11, 11,  3, 12,  9],
        [ 4,  6,  4, 15, 14,  4, 17],
        [ 6,  5, 15, 16, 13,  3,  5]],

       [[18, 18, 16, 15, 16, 17,  8],
        [ 6,  3, 16,  7,  5,  1, 17],
        [17, 11, 17,  1, 16,  8, 13],
        [19, 17,  6, 13, 12,  8, 18]]])

In [13]:
a7 = np.transpose(a6, (1,2,0))
a7

array([[[18, 18],
        [14, 18],
        [19, 16],
        [ 7, 15],
        [11, 16],
        [16, 17],
        [ 6,  8]],

       [[ 2,  6],
        [ 5,  3],
        [11, 16],
        [11,  7],
        [ 3,  5],
        [12,  1],
        [ 9, 17]],

       [[ 4, 17],
        [ 6, 11],
        [ 4, 17],
        [15,  1],
        [14, 16],
        [ 4,  8],
        [17, 13]],

       [[ 6, 19],
        [ 5, 17],
        [15,  6],
        [16, 13],
        [13, 12],
        [ 3,  8],
        [ 5, 18]]])